In [42]:
import pandas as pd
import requests

In [43]:
response = requests.get("https://newsapi.org/v2/everything?q=bitcoin&apiKey=ed8dc92685864caba98da594a84bddff")

In [44]:
df = pd.DataFrame(response.json()["articles"])
df

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': 'the-verge', 'name': 'The Verge'}",Robert Hart,I went looking for the AI weed vape that gives...,"The crypto weed vape found me on 4/20, the hig...",https://www.theverge.com/ai-artificial-intelli...,https://platform.theverge.com/wp-content/uploa...,2026-05-29T17:09:12Z,<ul><li></li></ul>\r\nGudtrip is the most ridi...
1,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,Why Would Someone Publicly Burn $8 Million Wor...,And another question: How do you burn bitcoin?,https://gizmodo.com/why-would-someone-publicly...,https://gizmodo.com/app/uploads/2026/05/bitcoi...,2026-05-28T20:12:23Z,"Earlier this week, someone burned 107 bitcoin ..."
2,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,The Word of God Now Comes With Bitcoin Rewards...,"In 2026, even the Bible is gamified.",https://gizmodo.com/the-word-of-god-now-comes-...,https://gizmodo.com/app/uploads/2026/06/Orange...,2026-06-20T19:26:03Z,"At first glance, Orange Bible looks like a sta..."
3,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,Largest US Banks to Launch Tokenization Networ...,The traditional banking industry has a long hi...,https://gizmodo.com/largest-us-banks-to-launch...,https://gizmodo.com/app/uploads/2025/10/gizmod...,2026-06-06T13:36:30Z,The largest banks in the United States are wor...
4,"{'id': None, 'name': 'Gizmodo.com'}",Rhett Jones,Crypto Promoters Say Blockchain Is the Future ...,Is crypto really the secret sauce that AI is m...,https://gizmodo.com/crypto-promoters-say-block...,https://gizmodo.com/app/uploads/2026/03/robot-...,2026-06-10T12:10:43Z,The crypto industry has been filled with many ...
...,...,...,...,...,...,...,...,...
92,"{'id': None, 'name': 'CoinDesk'}",Shaurya Malwa,"Mt. Gox moves 10,422 bitcoin worth $739 millio...","The 04:47 UTC Bitcoin block 952,072 transactio...",https://www.coindesk.com/markets/2026/06/02/mt...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-02T06:15:02Z,"Defunct bitcoin exchange Mt. Gox moved 10,422...."
93,"{'id': None, 'name': 'CoinDesk'}",Olivier Acuna,'Dr. Doom'-backed Atlas Capital CEO says bitco...,"Backed by economist Nouriel Roubini, a long-ti...",https://www.coindesk.com/markets/2026/06/04/dr...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-04T18:15:52Z,"Reza Bundy, chief executive of Atlas Capital a..."
94,"{'id': None, 'name': 'CoinDesk'}",Shaurya Malwa,Why a selloff in gold and silver is dragging b...,Bitcoin has long been lumped in with precious ...,https://www.coindesk.com/markets/2026/06/27/wh...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-27T18:11:04Z,The ongoing artificial intelligence stock fren...
95,"{'id': None, 'name': 'Gizmodo.com'}",Martín Nicolás Parolari,"Bitcoin no cayó por un ordenador cuántico, per...",No existe todavía una máquina cuántica capaz d...,https://es.gizmodo.com/bitcoin-no-cayo-por-un-...,https://es.gizmodo.com/app/uploads/2026/06/Dis...,2026-06-04T12:07:52Z,Bitcoin no amaneció roto. Nadie vació millones...
96,"{'id': None, 'name': 'Forbes'}","Ty Roush, Forbes Staff, \n Ty Roush, Forbes St...",Bitcoin Hits 21-Month Low As Expiring Crypto B...,The world’s leading cryptocurrency has lost mo...,https://www.forbes.com/sites/tylerroush/2026/0...,https://imageio.forbes.com/specials-images/ima...,2026-06-25T15:29:15Z,A three-day decline sent bitcoin to a 21-month...

In [45]:
df[["source_id" , "source_name"]] = df["source"].apply(pd.Series)
df

,source,author,title,description,url,urlToImage,publishedAt,content,source_id,source_name
0,"{'id': 'the-verge', 'name': 'The Verge'}",Robert Hart,I went looking for the AI weed vape that gives...,"The crypto weed vape found me on 4/20, the hig...",https://www.theverge.com/ai-artificial-intelli...,https://platform.theverge.com/wp-content/uploa...,2026-05-29T17:09:12Z,<ul><li></li></ul>\r\nGudtrip is the most ridi...,the-verge,The Verge
1,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,Why Would Someone Publicly Burn $8 Million Wor...,And another question: How do you burn bitcoin?,https://gizmodo.com/why-would-someone-publicly...,https://gizmodo.com/app/uploads/2026/05/bitcoi...,2026-05-28T20:12:23Z,"Earlier this week, someone burned 107 bitcoin ...",None,Gizmodo.com
2,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,The Word of God Now Comes With Bitcoin Rewards...,"In 2026, even the Bible is gamified.",https://gizmodo.com/the-word-of-god-now-comes-...,https://gizmodo.com/app/uploads/2026/06/Orange...,2026-06-20T19:26:03Z,"At first glance, Orange Bible looks like a sta...",None,Gizmodo.com
3,"{'id': None, 'name': 'Gizmodo.com'}",Kyle Torpey,Largest US Banks to Launch Tokenization Networ...,The traditional banking industry has a long hi...,https://gizmodo.com/largest-us-banks-to-launch...,https://gizmodo.com/app/uploads/2025/10/gizmod...,2026-06-06T13:36:30Z,The largest banks in the United States are wor...,None,Gizmodo.com
4,"{'id': None, 'name': 'Gizmodo.com'}",Rhett Jones,Crypto Promoters Say Blockchain Is the Future ...,Is crypto really the secret sauce that AI is m...,https://gizmodo.com/crypto-promoters-say-block...,https://gizmodo.com/app/uploads/2026/03/robot-...,2026-06-10T12:10:43Z,The crypto industry has been filled with many ...,None,Gizmodo.com
...,...,...,...,...,...,...,...,...,...,...
92,"{'id': None, 'name': 'CoinDesk'}",Shaurya Malwa,"Mt. Gox moves 10,422 bitcoin worth $739 millio...","The 04:47 UTC Bitcoin block 952,072 transactio...",https://www.coindesk.com/markets/2026/06/02/mt...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-02T06:15:02Z,"Defunct bitcoin exchange Mt. Gox moved 10,422....",None,CoinDesk
93,"{'id': None, 'name': 'CoinDesk'}",Olivier Acuna,'Dr. Doom'-backed Atlas Capital CEO says bitco...,"Backed by economist Nouriel Roubini, a long-ti...",https://www.coindesk.com/markets/2026/06/04/dr...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-04T18:15:52Z,"Reza Bundy, chief executive of Atlas Capital a...",None,CoinDesk
94,"{'id': None, 'name': 'CoinDesk'}",Shaurya Malwa,Why a selloff in gold and silver is dragging b...,Bitcoin has long been lumped in with precious ...,https://www.coindesk.com/markets/2026/06/27/wh...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-27T18:11:04Z,The ongoing artificial intelligence stock fren...,None,CoinDesk
95,"{'id': None, 'name': 'Gizmodo.com'}",Martín Nicolás Parolari,"Bitcoin no cayó por un ordenador cuántico, per...",No existe todavía una máquina cuántica capaz d...,https://es.gizmodo.com/bitcoin-no-cayo-por-un-...,https://es.gizmodo.com/app/uploads/2026/06/Dis...,2026-06-04T12:07:52Z,Bitcoin no amaneció roto. Nadie vació millones...,None,Gizmodo.com
96,"{'id': None, 'name': 'Forbes'}","Ty Roush, Forbes Staff, \n Ty Roush, Forbes St...",Bitcoin Hits 21-Month Low As Expiring Crypto B...,The world’s leading cryptocurrency has lost mo...,https://www.forbes.com/sites/tylerroush/2026/0...,https://imageio.forbes.com/specials-images/ima...,2026-06-25T15:29:15Z,A three-day decline sent bitcoin to a 21-month...,None,Forbes

In [46]:
df.drop(columns=['source'], inplace=True)

df.head()

,author,title,description,url,urlToImage,publishedAt,content,source_id,source_name
0,Robert Hart,I went looking for the AI weed vape that gives...,"The crypto weed vape found me on 4/20, the hig...",https://www.theverge.com/ai-artificial-intelli...,https://platform.theverge.com/wp-content/uploa...,2026-05-29T17:09:12Z,<ul><li></li></ul>\r\nGudtrip is the most ridi...,the-verge,The Verge
1,Kyle Torpey,Why Would Someone Publicly Burn $8 Million Wor...,And another question: How do you burn bitcoin?,https://gizmodo.com/why-would-someone-publicly...,https://gizmodo.com/app/uploads/2026/05/bitcoi...,2026-05-28T20:12:23Z,"Earlier this week, someone burned 107 bitcoin ...",None,Gizmodo.com
2,Kyle Torpey,The Word of God Now Comes With Bitcoin Rewards...,"In 2026, even the Bible is gamified.",https://gizmodo.com/the-word-of-god-now-comes-...,https://gizmodo.com/app/uploads/2026/06/Orange...,2026-06-20T19:26:03Z,"At first glance, Orange Bible looks like a sta...",None,Gizmodo.com
3,Kyle Torpey,Largest US Banks to Launch Tokenization Networ...,The traditional banking industry has a long hi...,https://gizmodo.com/largest-us-banks-to-launch...,https://gizmodo.com/app/uploads/2025/10/gizmod...,2026-06-06T13:36:30Z,The largest banks in the United States are wor...,None,Gizmodo.com
4,Rhett Jones,Crypto Promoters Say Blockchain Is the Future ...,Is crypto really the secret sauce that AI is m...,https://gizmodo.com/crypto-promoters-say-block...,https://gizmodo.com/app/uploads/2026/03/robot-...,2026-06-10T12:10:43Z,The crypto industry has been filled with many ...,None,Gizmodo.com

In [47]:
df.shape

(97, 9)

In [48]:
df.describe

<bound method NDFrame.describe of                                                author  \
0                                         Robert Hart
1                                         Kyle Torpey
2                                         Kyle Torpey
3                                         Kyle Torpey
4                                         Rhett Jones
..                                                ...
92                                      Shaurya Malwa
93                                      Olivier Acuna
94                                      Shaurya Malwa
95                            Martín Nicolás Parolari
96  Ty Roush, Forbes Staff, \n Ty Roush, Forbes St...

                                                title  \
0   I went looking for the AI weed vape that gives...
1   Why Would Someone Publicly Burn $8 Million Wor...
2   The Word of God Now Comes With Bitcoin Rewards...
3   Largest US Banks to Launch Tokenization Networ...
4   Crypto Promoters Say Blockchain Is the Future ...
..                                                ...
92  Mt. Gox moves 10,422 bitcoin worth $739 millio...
93  'Dr. Doom'-backed Atlas Capital CEO says bitco...
94  Why a selloff in gold and silver is dragging b...
95  Bitcoin no cayó por un ordenador cuántico, per...
96  Bitcoin Hits 21-Month Low As Expiring Crypto B...

                                          description  \
0   The crypto weed vape found me on 4/20, the hig...
1      And another question: How do you burn bitcoin?
2                In 2026, even the Bible is gamified.
3   The traditional banking industry has a long hi...
4   Is crypto really the secret sauce that AI is m...
..                                                ...
92  The 04:47 UTC Bitcoin block 952,072 transactio...
93  Backed by economist Nouriel Roubini, a long-ti...
94  Bitcoin has long been lumped in with precious ...
95  No existe todavía una máquina cuántica capaz d...
96  The world’s leading cryptocurrency has lost mo...

                                                  url  \
0   https://www.theverge.com/ai-artificial-intelli...
1   https://gizmodo.com/why-would-someone-publicly...
2   https://gizmodo.com/the-word-of-god-now-comes-...
3   https://gizmodo.com/largest-us-banks-to-launch...
4   https://gizmodo.com/crypto-promoters-say-block...
..                                                ...
92  https://www.coindesk.com/markets/2026/06/02/mt...
93  https://www.coindesk.com/markets/2026/06/04/dr...
94  https://www.coindesk.com/markets/2026/06/27/wh...
95  https://es.gizmodo.com/bitcoin-no-cayo-por-un-...
96  https://www.forbes.com/sites/tylerroush/2026/0...

                                           urlToImage           publishedAt  \
0   https://platform.theverge.com/wp-content/uploa...  2026-05-29T17:09:12Z
1   https://gizmodo.com/app/uploads/2026/05/bitcoi...  2026-05-28T20:12:23Z
2   https://gizmodo.com/app/uploads/2026/06/Orange...  2026-06-20T19:26:03Z
3   https://gizmodo.com/app/uploads/2025/10/gizmod...  2026-06-06T13:36:30Z
4   https://gizmodo.com/app/uploads/2026/03/robot-...  2026-06-10T12:10:43Z
..                                                ...                   ...
92  https://cdn.sanity.io/images/s3y3vcno/producti...  2026-06-02T06:15:02Z
93  https://cdn.sanity.io/images/s3y3vcno/producti...  2026-06-04T18:15:52Z
94  https://cdn.sanity.io/images/s3y3vcno/producti...  2026-06-27T18:11:04Z
95  https://es.gizmodo.com/app/uploads/2026/06/Dis...  2026-06-04T12:07:52Z
96  https://imageio.forbes.com/specials-images/ima...  2026-06-25T15:29:15Z

                                              content  source_id  source_name
0   <ul><li></li></ul>\r\nGudtrip is the most ridi...  the-verge    The Verge
1   Earlier this week, someone burned 107 bitcoin ...       None  Gizmodo.com
2   At first glance, Orange Bible looks like a sta...       None  Gizmodo.com
3   The largest banks in the United States are wor...       None  Gizmodo.com
4   The crypto industry has been filled with many ...       None  Gizmodo.com
..                                                ...        ...          ...
92  Defunct bitcoin exchange Mt. Gox moved 10,422....       None     CoinDesk
93  Reza Bundy, chief executive of Atlas Capital a...       None     CoinDesk
94  The ongoing artificial intelligence stock fren...       None     CoinDesk
95  Bitcoin no amaneció roto. Nadie vació millones...       None  Gizmodo.com
96  A three-day decline sent bitcoin to a 21-month...       None       Forbes

[97 rows x 9 columns]>

In [49]:
df.isnull().sum()

author          6
title           0
description     4
url             0
urlToImage      7
publishedAt     0
content         0
source_id      85
source_name     0
dtype: int64

In [ ]:
df.to_csv()